=== JavierSanabriaMiranda/F1Desktop/xml/circuito.dtd
<!ELEMENT circuitos (circuito+)>
<!ELEMENT circuito (nombre, longitudCircuito, anchura, fecha, hora, vueltas, localidad, pais, referencias, fotografias, videos?, coordenadas, tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitudCircuito (#PCDATA)>
<!ATTLIST longitudCircuito unidades CDATA #REQUIRED>
<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidades CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidades CDATA #REQUIRED>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT sector (#PCDATA)>

=== JavierSanabriaMiranda/F1Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuitos SYSTEM "circuito.dtd">
<circuitos>
    <circuito>
        <nombre>Circuito Internacional de Losail</nombre>
        <longitudCircuito unidades="metros">5.419</longitudCircuito>
        <anchura unidades="metros">12</anchura>
        <fecha>01-12-2024</fecha>
        <hora>17:00</hora>
        <vueltas>57</vueltas>
        <localidad>Losail</localidad>
        <pais>Qatar</pais>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Losail</referencia>
            <referencia>https://www.formula1.com/en/racing/2024/qatar</referencia>
        </referencias>
        <fotografias>
            <fotografia>circuito_losail_1.jpg</fotografia>
            <fotografia>circuito_losail_2.jpg</fotografia>
        </fotografias>
        <coordenadas>
            <longitud>51°27'00.8"E</longitud>
            <latitud>25°29'17.6"N</latitud>
            <altitud unidades="metros sobre el nivel del mar">13</altitud>
        </coordenadas>
        <tramos>
            <tramo>
                <distancia unidades="metros">510</distancia>
                <coordenadas>
                    <longitud>51°26'55.4"E</longitud>
                    <latitud>25°29'35.5"N</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">194</distancia>
                <coordenadas>
                    <longitud>51°26'55.4"E</longitud>
                    <latitud>25°29'35.5"N</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
        </tramos>
    </circuito>
</circuitos>
