=== JavierSanabriaMiranda/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:float" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:float" />
	<xs:element name="latitud" type="xs:float" />
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:float" />
</xs:schema>

=== JavierSanabriaMiranda/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <circuito>
        <nombre>Circuito Internacional de Losail</nombre>
        <longitudCircuito unidades="metros">5.419</longitudCircuito>
        <anchura unidades="metros">12</anchura>
        <fecha>2024-12-01</fecha>
        <hora>17:00:00</hora>
        <vueltas>57</vueltas>
        <localidad>Losail</localidad>
        <pais>Qatar</pais>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Losail</referencia>
            <referencia>https://www.formula1.com/en/racing/2024/qatar</referencia>
            <referencia>https://www.dazn.com/es-ES/news/motor/gp-qatar-motogp-losail-fecha-hora-canal-tv-donde-ver-online-gran-premio-mundial-motociclismo/1xz47zze0yue617mquzbnbyrl4</referencia>
        </referencias>
        <fotografias>
            <fotografia>circuito_losail_1.jpg</fotografia>
            <fotografia>circuito_losail_2.jpg</fotografia>
        </fotografias>
        <coordenadas>
    <longitud>51.450222</longitud>
    <latitud>25.488222</latitud>
    <altitud unidades="metros sobre el nivel del mar">13</altitud>
        </coordenadas>
        <tramos>
            <tramo>
                <distancia unidades="metros">510</distancia>
                <coordenadas>
                    <longitud>51.448722</longitud>
                    <latitud>25.493194</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">194</distancia>
                <coordenadas>
                    <longitud>51.448722</longitud>
                    <latitud>25.493194</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">168</distancia>
                <coordenadas>
                    <longitud>51.449875</longitud>
                    <latitud>25.492523</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">137</distancia>
                <coordenadas>
                    <longitud>51.450738</longitud>
                    <latitud>25.493104</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">162</distancia>
                <coordenadas>
                    <longitud>51.450768</longitud>
                    <latitud>25.494440</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">398</distancia>
                <coordenadas>
                    <longitud>51.453472</longitud>
                    <latitud>25.497146</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">137</distancia>
                <coordenadas>
                    <longitud>51.454706</longitud>
                    <latitud>25.496359</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">150</distancia>
                <coordenadas>
                    <longitud>51.453869</longitud>
                    <latitud>25.495071</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">118</distancia>
                <coordenadas>
                    <longitud>51.453118</longitud>
                    <latitud>25.494268</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">89</distancia>
                <coordenadas>
                    <longitud>51.453718</longitud>
                    <latitud>25.493938</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">280</distancia>
                <coordenadas>
                    <longitud>51.456244</longitud>
                    <latitud>25.494853</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">172</distancia>
                <coordenadas>
                    <longitud>25.493870</longitud>
                    <latitud>51.456695</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">220</distancia>
                <coordenadas>
                    <longitud>25.492107</longitud>
                    <latitud>51.455628</latitud>
                    <altitud unidades="metros sobre el nivel del mar">11</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">199</distancia>
                <coordenadas>
                    <longitud>25.491531</longitud>
                    <latitud>51.453831</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">86</distancia>
                <coordenadas>
                    <longitud>25.490829</longitud>
                    <latitud>51.453691</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">308</distancia>
                <coordenadas>
                    <longitud>25.489812</longitud>
                    <latitud>51.456615</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">140</distancia>
                <coordenadas>
                    <longitud>25.489938</longitud>
                    <latitud>51.457907</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">86</distancia>
                <coordenadas>
                    <longitud>25.490035</longitud>
                    <latitud>51.458728</latitud>
                    <altitud unidades="metros sobre el nivel del mar">12</altitud>
                </coordenadas>
                <sector>3</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">218</distancia>
                <coordenadas>
                    <longitud>25.488515</longitud>
                    <latitud>51.460016</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>3</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">183</distancia>
                <coordenadas>
                    <longitud>25.486980</longitud>
                    <latitud>51.458991</latitud>
                    <altitud unidades="metros sobre el nivel del mar">14</altitud>
                </coordenadas>
                <sector>3</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">305</distancia>
                <coordenadas>
                    <longitud>25.487348</longitud>
                    <latitud>51.455976</latitud>
                    <altitud unidades="metros sobre el nivel del mar">14</altitud>
                </coordenadas>
                <sector>3</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">439</distancia>
                <coordenadas>
                    <longitud>25.484064</longitud>
                    <latitud>51.453777</latitud>
                    <altitud unidades="metros sobre el nivel del mar">13</altitud>
                </coordenadas>
                <sector>3</sector>
            </tramo>
            <tramo>
                <distancia unidades="metros">107</distancia>
                <coordenadas>
                    <longitud>25.484181</longitud>
                    <latitud>51.452704</latitud>
                    <altitud unidades="metros sobre el nivel del mar">14</altitud>
